### ISSUE TITLE
Unable to type password

### ISSUE THREAD

**Issue by taophp** [authcrunch/authcrunch.github.io#60]
After submitting my username, I got an "Unauthorized" page, without be able to ever type my password.

In the log, I can see this line:
```
caddy    | {"level":"debug","ts":1711108495.9933956,"logger":"security","msg":"failed sandbox request","session_id":"d3XyHZGxXv08oWHOsRv2OWvkcPFYGUkVnt32lbGtP3U5D","request_id":"34a7cc42-7cfe-4e9f-a7ef-31cb28da1d84","error":"sandbox secret not found"}
```

I'm working with Docker-compose.

The Dockerfile I used to build Caddy:
```
FROM my_xcaddy AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/infogulch/xtemplate-caddy
FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

My docker-compose.yml file:
```
version: "3.7"

services:
  caddy:
    build: ./dockers/caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: './Caddyfile'
        target: /etc/caddy/Caddyfile
        read_only: true
      - ./site:/usr/share/caddy
      - ./data:/data
  maildev:
    image: maildev/maildev
    container_name: maildev
```

And, finally, my Caddyfile (strongly inspired from https://github.com/authcrunch/authcrunch.github.io/blob/main/assets/conf/local/Caddyfile):
```
{
	debug

	order authenticate before respond
	order authorize before basicauth

	security {
		local identity store localdb {
			realm local
			path /data/caddy/users.json
		}

		authentication portal myportal {
			crypto default token lifetime 3600
			enable identity store localdb
			cookie domain localhost
			ui {
				links {
					"My Website" https://test.localhost/ icon "las la-star"
					"Guests" https://test.localhost/guests icon "las la-star"
					"Users" https://test.localhost/users icon "las la-star"
					"Admins" https://test.localhost/admins icon "las la-star"
					"My Identity" "/whoami" icon "las la-user"
				}
			}
			transform user {
				match origin local
				action add role authp/user
				ui link "Portal Settings" /settings icon "las la-cog"
			}
		}

		authorization policy guests_policy {
			set auth url https://auth.localhost/
			allow roles authp/admin authp/user
			acl rule {
				comment allow guests only
				match role guest authp/guest
				allow stop log info
			}
			acl rule {
				comment default deny
				match any
				deny log warn
			}
		}

		authorization policy users_policy {
			set auth url https://auth.localhost/
			allow roles authp/admin authp/user
			acl rule {
				comment allow users
				match role authp/user
				allow stop log info
			}
			acl rule {
				comment default deny
				match any
				deny log warn
			}
		}

		authorization policy admins_policy {
			set auth url https://auth.localhost/
			allow roles authp/admin authp/user
			acl rule {
				comment allow users
				match role authp/user
				allow stop log info
			}
			acl rule {
				comment default deny
				match any
				deny log warn
			}
		}
	}
}

auth.localhost {
	tls internal
	route {
		authenticate with myportal
	}
}

test.localhost {
	tls internal
	route /guests* {
		authorize with guests_policy
		respond * "test - guests only" 200
	}

	route /users* {
		authorize with users_policy
		respond * "test - users" 200
	}

	route /admins* {
		authorize with admins_policy
		respond * "test - admins" 200
	}

	route {
		respond "test is running"
	}
}
```
What's wrong with this ?
